symbol: EURUSD
exchange: oanda
account_balance: 100000
risk_per_trade: 0.01   # 1%
max_positions: 1
leverage: 30
top_k_depth: 10
snapshot_stride_ms: 100
data_path: data/raw/EURUSD
processed_path: data/processed/EURUSD
